### ISSUE TITLE
Use osm2pgsql multi-geometry option?

### ISSUE THREAD

**Issue by alexandervlpl** [yannos/Beautiful_OSM_in_QGIS#1]
Great work on this! Just a thought: wouldn't using the `--multi-geometry` option solve the national parks problem? From the osm2pgsql man page:

> -G|--multi-geometry
>
> Normally  osm2pgsql splits multi-part geometries into separate database rows per part.  A single OSM id can therefore have several rows. With this option, PostgreSQL instead generates multi-geometry features in the PostgreSQL tables.

This way you shouldn't need the `ST_Multi(ST_Collect("polygon_geom"))` stuff. I'll try it if I get the chance.

**Comment by yannos** [comment]
Thanks. From the docs and memory I don't think we tried `--multi-geometry` so that could be a useful step. I like the idea as it could yield other zones currently missed due to the polygon issue - the work-around/correction is only for national parks but there could be others.

Let me know how the attempt goes. If it looks good I'll look to merge into main branch

**Comment by yannos** [comment]
Separately, do you have or know anyone who has GIS skills for hire? Or know of anywhere good to look / suitable platforms?

We're looking for a few steps:

- data collection for the db (postgres)
- geo analysis (eg if X is close to Y, how far away is nearest Z; whats the total population withing X km of each Z? that sort of thing)
- mapping to show the results of the steps above.

We've tried Upwork and PPH (UK based) and GISTribe on Twitter.

Thanks

**Comment by alexandervlpl** [comment]
Yes, it's not just national parks. Most OSM-based online map tiles are now rendered with MULTIPOLYGONs to avoid duplicate labels and other artifacts. There can be a performance impact though, especially if you're doing analysis/calculations (sounds like you are). Some details [here](http://www.paulnorman.ca/blog/2014/03/osm2pgsql-multipolygons/).

Although I'm mostly occupied with my own project now, I still do freelance GIS work like this from time to time. :) Don't hesitate to [get in touch](mailto:admin@inkatlas.com).

Can't comment on PPH or GISTribe, but it's definitely getting harder to find a good professional on Upwork!

**Comment by yannos** [comment]
> Great work on this! Just a thought: wouldn't using the `--multi-geometry` option solve the national parks problem? From the osm2pgsql man page:
> 
> > -G|--multi-geometry
> > Normally  osm2pgsql splits multi-part geometries into separate database rows per part.  A single OSM id can therefore have several rows. With this option, PostgreSQL instead generates multi-geometry features in the PostgreSQL tables.
> 
> This way you shouldn't need the `ST_Multi(ST_Collect("polygon_geom"))` stuff. I'll try it if I get the chance.

@alexandervlpl  did you ever try this?
